name: Toolchain

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on: [push, pull_request]

jobs:

  toolchain:

    runs-on: ubuntu-latest
    container:
      image: koreader/kobase:2.0.0-22.04

    strategy:
      fail-fast: false
      matrix:
        tc: [
          bookeen,
          cervantes,
          kindle,
          kindle5,
          kindlehf,
          kindlepw2,
          kobo,
          kobov4,
          kobov5,
          nickel,
          pocketbook,
          remarkable,
          remarkable-aarch64,
        ]

    env:
      CCACHE_DIR: "${{ format('{0}/ccache', github.workspace) }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Install deps
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y bison flex gawk gperf help2man libncurses-dev libtool-bin rsync texinfo

      - name: Restore build cache
        id: cache-restore
        uses: actions/cache/restore@v6
        with:
          path: &CACHE_PATHS |
            ${{ env.CCACHE_DIR }}
          key: ${{ matrix.tc }}-cache-${{ github.sha }}-${{ github.run_number }}
          restore-keys: |
            ${{ matrix.tc }}-cache-${{ github.sha }}-
            ${{ matrix.tc }}-cache-

      - name: Setup build cache
        if: steps.build-restore.outputs.cache-hit != 'true'
        run: |
          set -x
          ccache --version
          ccache --zero-stats
          ccache --max-size=1G
          ccache --show-config
          ccache_bindir='/usr/local/ccache'
          sudo mkdir "${ccache_bindir}"
          for f in /usr/bin/{c++,cc,g++,gcc,x86_64-*-gcc,x86_64-*-g++}; do
            [[ -x "$f" ]] || exit $?
            sudo ln --symbolic --no-dereference --force --relative /usr/local/bin/ccache "$ccache_bindir/${f##*/}"
          done
          printf '%s\n' "${ccache_bindir}" >>"${GITHUB_PATH}"

      - name: Generate toolchain
        run: ./gen-tc.sh ${{ matrix.tc }}

      - name: Clean build cache
        if: always()
        run: |
          set -x
          ccache --cleanup >/dev/null
          ccache --show-stats --verbose

      - name: Save build cache
        uses: actions/cache/save@v6
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: *CACHE_PATHS
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Tar artifacts
        run: tar -C ~ -caf ${{ matrix.tc }}.tar.zst x-tools

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: ${{ matrix.tc }}
          path: ${{ matrix.tc }}.tar.zst

  release:

    if: ${{ !cancelled() && startsWith(github.ref, 'refs/tags/') }}
    needs: toolchain

    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: artifacts
          skip-decompress: true

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Check if release already exists.
          gh release list --json name,tagName,isDraft,createdAt,publishedAt | jq --color-output --exit-status --raw-output '.[] | select(.tagName == "${{ github.ref_name }}") | if .tagName == "" then halt_error end' ||
          # And create it if it does not.
          gh release create '${{ github.ref_name }}' --draft --notes-file .github/default_release_notes.md --title 'koxtoolchain ${{ github.ref_name }}' --verify-tag

      - name: Upload release artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload '${{ github.ref_name }}' artifacts/* --clobber
